version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      #- $(aws ecr get-login --region ap-south-1 --no-include-email)
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 905418306616.dkr.ecr.ap-south-1.amazonaws.com
      - # Replace with this to your repository URI
      - REPOSITORY_URI=905418306616.dkr.ecr.ap-south-1.amazonaws.com/angular-ecr
      - IMAGE_TAG=angular-routing-$CODEBUILD_BUILD_ID
  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
artifacts:
  files:
    - imagedefinitions.json
